apiVersion: v1
kind: ConfigMap
metadata:
  name: kubemate-config
  namespace: kubemate
  labels:
    app: kubemate
data:
  database-url: "postgresql://$(DB_USER):$(DB_PASSWORD)@kubemate-postgres:5432/kubemate"
