apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubemate-backend-pvc
  namespace: kubemate
  labels:
    app: kubemate-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
