apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubemate-postgres-pvc
  namespace: kubemate
  labels:
    app: kubemate-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
