apiVersion: v1
kind: Secret
metadata:
  name: kubemate-secrets
  namespace: kubemate
  labels:
    app: kubemate
type: Opaque
stringData:
  # IMPORTANT: Change these values before deploying to production!
  # Generate secure random values for production use
  db-user: "kubemate"
  db-password: "acuW-eoQICOoTMDXnTNEoutH5QkrzTxj8nESHUriK6Q="
  flask-secret-key: "7yDMUHxf3dCduhRAXMPDVXMutp1ydFBfB65yn6cB4cM="
  encryption-key: "akzlFw4NfhMfrGNv9mTTvjTAJzDJPyY3QMUtMrpUU40="
