apiVersion: v1
kind: Service
metadata:
  name: kubemate-postgres
  namespace: kubemate
  labels:
    app: kubemate-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: kubemate-postgres
  type: ClusterIP
