apiVersion: v1
kind: Service
metadata:
  name: kubemate-backend
  namespace: kubemate
  labels:
    app: kubemate-backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: kubemate-backend
  type: ClusterIP
